repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        pass_filenames: false
        require_serial: true
      - id: ci
        name: ci
        entry: make ci
        language: system
        pass_filenames: false
        require_serial: true
default_language_version:
  python: python
